    spring:
      application:
        name: current-issue
      config:
        import: "configserver:"
      cloud:
        config:
          discovery:
            enabled: true
            service-id: "SERVICE-CONFIG"
          fail-fast: true