
  spring:
    config:
      import: "configserver:"
    cloud:
      config:
        discovery:
          enabled: true
          service-id: "SERVICE-CONFIG"
        fail-fast: true
    application:
      name: user-service

